lib/hw06_web/router.ex
defmodule Hw06Web.Router do
  use Hw06Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Hw06Web.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end
  
  pipeline :ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug Hw06Web.Plugs.FetchSession # FIXME: "FetchUser"
  end

  scope "/", Hw06Web do
    pipe_through :browser

    get "/", PageController, :index
    get "/task_report", TaskController, :task_report
    
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
    resources "/tasks", TaskController
    resources "/task_times", TaskTimeController
  end
  
  scope "/ajax", Hw06Web do
    pipe_through :ajax
    resources "/time_blocks", TimeBlockController, except: [:new, :edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Hw06Web do
  #   pipe_through :api
  # end
end

lib/hw06/tasks.ex
defmodule Hw06.Tasks do
  @moduledoc """
  The Tasks context.
  """

  import Ecto.Query, warn: false
  alias Hw06.Repo

  alias Hw06.Tasks.Task

  @doc """
  Returns the list of tasks.

  ## Examples

      iex> list_tasks()
      [%Task{}, ...]

  """
  def list_tasks do
    Repo.all(Task)
  end

  @doc """
  Gets a single task.

  Raises `Ecto.NoResultsError` if the Task does not exist.

  ## Examples

      iex> get_task!(123)
      %Task{}

      iex> get_task!(456)
      ** (Ecto.NoResultsError)

  """
  def get_task!(id) do
    Repo.one! from t in Task,
      where: t.id == ^id,
      preload: [:time_blocks]
  end

  @doc """
  Creates a task.

  ## Examples

      iex> create_task(%{field: value})
      {:ok, %Task{}}

      iex> create_task(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_task(attrs \\ %{}) do
    %Task{}
    |> Task.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a task.

  ## Examples

      iex> update_task(task, %{field: new_value})
      {:ok, %Task{}}

      iex> update_task(task, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_task(%Task{} = task, attrs) do
    task
    |> Task.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Task.

  ## Examples

      iex> delete_task(task)
      {:ok, %Task{}}

      iex> delete_task(task)
      {:error, %Ecto.Changeset{}}

  """
  def delete_task(%Task{} = task) do
    Repo.delete(task)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking task changes.

  ## Examples

      iex> change_task(task)
      %Ecto.Changeset{source: %Task{}}

  """
  def change_task(%Task{} = task) do
    Task.changeset(task, %{})
  end
  
  def get_assigned_count(user_id) do
    Repo.one(from t in Task, select: count("*"), where: t.assigned_user == ^user_id)
  end
  
  def get_completed_count do
    Repo.one(from t in Task, select: count("*"), where: t.completed == true)
  end
  
  def get_open_count do
    Repo.one(from t in Task, select: count("*"), where: t.completed == false)
  end
  
  def get_tasks_for_underlings(underlings) do
    ids = Enum.map(underlings, fn underling -> underling.id end)
    query = from(t in Task, where: t.assigned_user in ^ids, select: t)
    Repo.all(query)
  end
end

lib/hw06/tasks/task.ex
defmodule Hw06.Tasks.Task do
  use Ecto.Schema
  import Ecto.Changeset


  schema "tasks" do
    field :completed, :boolean, default: false
    field :description, :string
    field :title, :string
    field :assigned_user, :id, default: nil
    has_many :time_blocks, Hw06.TimeBlocks.TimeBlock

    timestamps()
  end

  @doc false
  def changeset(task, attrs) do
    task
    |> cast(attrs, [:title, :description, :completed, :assigned_user])
    |> validate_required([:title, :description])
  end
end

lib/hw06_web/controllers/task_controller.ex
defmodule Hw06Web.TaskController do
  use Hw06Web, :controller

  alias Hw06.Tasks
  alias Hw06.Tasks.Task
  alias Hw06.Users
  
  plug :authenticate_user

  def index(conn, _params) do
    tasks = Tasks.list_tasks()
    render(conn, "index.html", tasks: tasks)
  end

  def new(conn, _params) do
    changeset = Tasks.change_task(%Task{})
    render(conn, "new.html", changeset: changeset, users: Users.get_for_select_managed(conn.assigns.current_user.id))
  end

  def create(conn, %{"task" => task_params}) do
    case Tasks.create_task(task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task created successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    render(conn, "show.html", task: task)
  end

  def edit(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    changeset = Tasks.change_task(task)
    render(conn, "edit.html", task: task, changeset: changeset, users: Users.get_for_select_managed(conn.assigns.current_user.id))
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = Tasks.get_task!(id)

    case Tasks.update_task(task, task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task updated successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", task: task, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    {:ok, _task} = Tasks.delete_task(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: Routes.task_path(conn, :index))
  end
  
  def task_report(conn, _params) do
    underlings = Users.get_underlings(conn.assigns.current_user.id)
    tasks = Tasks.get_tasks_for_underlings(underlings)
    render(conn, "task_report.html", tasks: tasks)
  end
  
  def authenticate_user(conn, _params) do
    if conn.assigns.current_user != nil do
      conn
    else
      conn
      |> put_flash(:error, "Please log in to view this page.")
      |> redirect(to: Routes.page_path(conn, :index))
      |> halt()
    end
  end
end

lib/hw06_web/views/task_view.ex
defmodule Hw06Web.TaskView do
  use Hw06Web, :view
end

lib/hw06_web/templates/task/edit.html.eex
<span><%= link "Back", to: Routes.task_path(@conn, :index), class: "btn btn-primary"  %></span>
<div class="card mt-2">
  <h5 class="card-header">Edit Task</h5>
  <div class="card-body">
      <%= if @task.assigned_user == @current_user.id || @current_user.admin do %>
        <%= link "Delete", to: Routes.task_path(@conn, :delete, @task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger" %>
      <% end %>
    <%= render "edit_form.html", Map.put(assigns, :action, Routes.task_path(@conn, :update, @task, @users)) %>
  </div>
</div>

lib/hw06_web/templates/task/edit_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title, class: "form-control" %>
  <%= error_tag f, :title %>
  <br />
  <%= label f, :description %>
  <%= textarea f, :description, class: "form-control" %>
  <%= error_tag f, :description %>
  <br />
  
  <%= label f, :assigned_user %>
  <%= select f, :assigned_user, @users, class: "form-control" %>
  <%= error_tag f, :assigned_user %>
  <br />
  
  <%= label f, :completed %>
  <%= checkbox f, :completed %>
  <%= error_tag f, :completed %>
  
  <div>
    <%= submit "Save", class: "btn btn-success" %>
  </div>
<% end %>

lib/hw06_web/templates/task/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :description %>
  <%= text_input f, :description %>
  <%= error_tag f, :description %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/hw06_web/templates/task/index.html.eex
<% alias Hw06.Users %>
<% alias Hw06.Tasks %>
<h1>Tasks</h1>
<span><%= link "New Task", to: Routes.task_path(@conn, :new), class: "btn btn-success mt-2 mb-2" %></span>
<h3>Your Tasks</h3>
<%= if Tasks.get_assigned_count(@current_user.id) == 0 do %>
  <em>You have no assigned tasks!</em>
<% else %>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Completed</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for task <- @tasks do %>
      <%= if task.assigned_user == @current_user.id do %>
        <tr>
          <td><%= task.title %></td>
          <td><%= task.description %></td>
          <td>
            <%= if task.completed do %>
              <i class="fas fa-2x fa-check-circle green"></i>
            <% else %>
              <i class="fas fa-2x fa-times-circle red"></i>
            <% end %>
          </td>
          <td>
            <%= link "Show", to: Routes.task_path(@conn, :show, task), class: "btn btn-primary" %>
            <%= link "Edit", to: Routes.task_path(@conn, :edit, task), class: "btn btn-warning" %>
            <%= link "Log Work", to: Routes.task_time_path(@conn, :new, %{:task_id => task.id}), class: "btn btn-warning" %>
            <%= link "Delete", to: Routes.task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<% end %>
<hr>
<h3>All Tasks</h3>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Completed</th>
      <th>Assignee</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for task <- @tasks do %>
        <tr>
          <td><%= task.title %></td>
          <td><%= task.description %></td>
          <td>
            <%= if task.completed do %>
              <i class="fas fa-2x fa-check-circle green"></i>
            <% else %>
              <i class="fas fa-2x fa-times-circle red"></i>
            <% end %>
          </td>
          <td>
            <%= if task.assigned_user != nil do %>
              <%= Users.get_user!(task.assigned_user).email %>
            <% else %>
              <em>No assignee</em>
            <% end %>
          </td>
          <td>
            <%= link "Show", to: Routes.task_path(@conn, :show, task), class: "btn btn-primary" %>
            <%= link "Edit", to: Routes.task_path(@conn, :edit, task), class: "btn btn-warning" %>
            <%= if task.assigned_user == @current_user.id || @current_user.admin do %>
              <%= link "Log Work", to: Routes.task_time_path(@conn, :new, %{:task_id => task.id}), class: "btn btn-warning" %>
              <%= link "Delete", to: Routes.task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger" %>
            <% end %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>

lib/hw06_web/templates/task/new.html.eex
<span><%= link "Back", to: Routes.task_path(@conn, :index), class: "btn btn-primary"  %></span>
<div class="card mt-2">
  <h5 class="card-header">New Task</h5>
  <div class="card-body">
    <%= render "new_form.html", Map.put(assigns, :action, Routes.task_path(@conn, :create)) %>
  </div>
</div>

lib/hw06_web/templates/task/new_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title, class: "form-control" %>
  <%= error_tag f, :title %>
  <br />
  
  <%= label f, :description %>
  <%= textarea f, :description, class: "form-control" %>
  <%= error_tag f, :description %>
  <br />
  
  <%= label f, :assigned_user %>
  <%= select f, :assigned_user, @users, class: "form-control" %>
  <%= error_tag f, :assigned_user %>
  <br />

  <div>
    <%= submit "Save", class: "btn btn-success" %>
  </div>
<% end %>

lib/hw06_web/templates/task/show.html.eex
<% alias Hw06.Users %>
<% alias Hw06.TimeBlocks %>
<span><%= link "Back", to: Routes.task_path(@conn, :index), class: "btn btn-primary" %></span>
<div class="card mt-2">
  <h3 class="card-header">Show Task 
    <%= if @task.assigned_user == @current_user.id do %>
      <%= link "Delete", to: Routes.task_path(@conn, :delete, @task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger right-btn" %>
    <% end %>
    <%= link "Edit", to: Routes.task_path(@conn, :edit, @task), class: "btn btn-warning right-btn mr-2" %>
  </h3>
  <div class="card-body">
    <div class="row">
      <div class="col-lg-6">
        <strong>Title:</strong>
        <%= @task.title %> <br />
        <strong>Description:</strong>
        <%= @task.description %> <br />
        <strong>Assignee:</strong>
        <%= if @task.assigned_user != nil do %>
          <%= Users.get_name(@task.assigned_user) %>
        <% else %>
          <em>None</em>
        <% end %><br />
        <strong>Completed:</strong>
        <%= if @task.completed do %>
        <i class="fas fa-check-circle green"></i>
        <% else %>
        <i class="fas fa-times-circle red"></i>
        <% end %>
      </div>
      <div class="col-lg-6">
        <div class="card">
          <h5 class="card-header">Logged Work
            <%= if @task.assigned_user == @current_user.id do %>
              <% time_block = TimeBlocks.get_last_time_block(@task.id) %>
              <%= if time_block && time_block.end == nil do %>
                <button id="end-work-button"
                    data-block-id="<%= time_block.id %>"
                    class="btn btn-danger right-btn">End Work</button>
              <% else %>
                <button id="start-work-button"
                    data-task-id="<%= @task.id %>"
                    data-user-id="<%= @current_user.id %>"
                    class="btn btn-success right-btn">Start Work</button>
              <% end %>
            <% end %>
          </h5>
          <div class="card-body">
            <%= if @task.time_blocks == 0 do %>
              <em>No logged work!</em>
            <% else %>
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>User</th>
                  <th>Start</th>
                  <th>End</th>
                  <th></th>
                </tr>
              </thead>
            <%= for time_block <- @task.time_blocks do %>
            <tr>
              <td><%= Users.get_name(time_block.user_id) %></td>
              <td><%= "#{time_block.start.year}-#{time_block.start.month}-#{time_block.start.day}, #{time_block.start.hour}:#{time_block.start.minute}"  %></td>
              <td>
                <%= if time_block.end == nil do %>
                  <em>Currently working</em>
                <% else %>
                  <%= "#{time_block.end.year}-#{time_block.end.month}-#{time_block.end.day}, #{time_block.end.hour}:#{time_block.end.minute}"  %>
                <% end %>
              </td>
              <%= if @task.assigned_user == @current_user.id do %>
              <td><%= link "Delete", to: Routes.time_block_path(@conn, :delete, time_block), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger" %></td>
              <% end %>
            </tr>
            <% end %>
          </table>
          <% end %>
          </div>
        </div>
        
      </div>
    </div>
  </div>
</div>

lib/hw06_web/templates/task/task_report.html.eex
<% alias Hw06.Users %>
<% alias Hw06.Tasks %>
<h1>Tasks</h1>
<span><%= link "New Task", to: Routes.task_path(@conn, :new), class: "btn btn-success mt-2 mb-2" %></span>
<h3>Your Underlings' Tasks</h3>
<%= if length(@tasks) == 0 do %>
  <em>Your underlings have no tasks!</em>
<% else %>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Completed</th>
      <th>Assignee</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for task <- @tasks do %>
        <tr>
          <td><%= task.title %></td>
          <td><%= task.description %></td>
          <td>
            <%= if task.completed do %>
              <i class="fas fa-2x fa-check-circle green"></i>
            <% else %>
              <i class="fas fa-2x fa-times-circle red"></i>
            <% end %>
          </td>
          <td>
            <%= if task.assigned_user != nil do %>
              <%= Users.get_user!(task.assigned_user).email %>
            <% else %>
              <em>No assignee</em>
            <% end %>
          </td>
          <td>
            <%= link "Show", to: Routes.task_path(@conn, :show, task), class: "btn btn-primary" %>
            <%= link "Edit", to: Routes.task_path(@conn, :edit, task), class: "btn btn-warning" %>
            <%= if task.assigned_user == @current_user.id || @current_user.admin do %>
              <%= link "Log Work", to: Routes.task_time_path(@conn, :new, %{:task_id => task.id}), class: "btn btn-warning" %>
              <%= link "Delete", to: Routes.task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger" %>
            <% end %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>
<% end %>