lib/hw06_web/router.ex
defmodule Hw06Web.Router do
  use Hw06Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Hw06Web.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end
  
  pipeline :ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug Hw06Web.Plugs.FetchSession # FIXME: "FetchUser"
  end

  scope "/", Hw06Web do
    pipe_through :browser

    get "/", PageController, :index
    get "/task_report", TaskController, :task_report
    
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
    resources "/tasks", TaskController
    resources "/task_times", TaskTimeController
  end
  
  scope "/ajax", Hw06Web do
    pipe_through :ajax
    resources "/time_blocks", TimeBlockController, except: [:new, :edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Hw06Web do
  #   pipe_through :api
  # end
end

lib/hw06_web/templates/page/index.html.eex
<div class="row">
    <div class="col-12">
        <h1>Welcome to the Task Tracker!</h1>
        <hr>
    </div>
</div>
<%= if @current_user == nil do %>
<div class="row text-center">
    <div class="col-lg-12" align="center">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <%= form_for @conn, Routes.session_path(@conn, :create), fn f -> %>
                <label>Log in with your email</label>
                <%= text_input f, :email, class: "form-control" %><br />
                <%= submit "Login", class: "btn btn-success" %>
              <% end %>
            No account? <%= link "Register", to: Routes.user_path(@conn, :new) %>
          </div>
        </div>
    </div>
</div>
<% else %>
<h5><em>Task Summary</em></h5>
<div class="row mt-3">
    <div class="col-lg-4">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">Your Tasks</h5>
            <p class="card-text"><%= @assigned %> tasks</p>
          </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">Open Tasks</h5>
            <p class="card-text"><%= @completed %> tasks</p>
          </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">Completed Tasks</h5>
            <p class="card-text"><%= @open %> tasks</p>
          </div>
        </div>
    </div>
</div>
<% end %>